#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker6"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "76090de5965f4458a8e3fc5711532489" }
]
